test:
  sessions:
    default:
      database: trade_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      database: trade_production
      hosts:
        - localhost:27017

staging:
  sessions:
    default:
      database: trade_staging
      hosts:
        - localhost:27017